"use client";
import React from "react";
import _styles from "./css/classes.module.css";
import * as _utils from "./utils";
import Block from "./_Builtin/Block";
import DOM from "./_Builtin/DOM";
import DropdownList from "./_Builtin/DropdownList";
import DropdownToggle from "./_Builtin/DropdownToggle";
import DropdownWrapper from "./_Builtin/DropdownWrapper";
import Link from "./_Builtin/Link";
import List from "./_Builtin/List";
import ListItem from "./_Builtin/ListItem";
import NotSupported from "./_Builtin/NotSupported";
import SearchButton from "./_Builtin/SearchButton";
import SearchForm from "./_Builtin/SearchForm";
import SearchInput from "./_Builtin/SearchInput";
import { ButtonMain } from "./ButtonMain";
import { IconArrow } from "./IconArrow";
import { IconSearch } from "./IconSearch";

export function Menu({ as: _Component = Block, variant = "Mobile" }) {
  const _styleVariantMap = {
    Mobile: "",
    Desktop: "w-variant-23049969-09ac-2789-520b-3c6ae895bbc6",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <_Component
      aria-label="Main"
      className={_utils.cx(_styles, "nav_links_component", _activeStyleVariant)}
      tag="nav"
    >
      <List
        className={_utils.cx(_styles, "nav_links_wrap", _activeStyleVariant)}
        tag="ul"
        unstyled={true}
      >
        <ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            delay={400}
            hover={true}
            tag="div"
          >
            <DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              data-state="expanded"
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_links_text",
                  _activeStyleVariant
                )}
                tag="div"
              >
                {"Services"}
              </Block>
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_links_svg",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconArrow direction="Bottom" />
              </Block>
            </DropdownToggle>
            <DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_main_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_main_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "nav_dropdown_main_scroll",
                    _activeStyleVariant
                  )}
                  data-lenis-prevent=""
                  tag="div"
                >
                  <List
                    className={_utils.cx(
                      _styles,
                      "nav_dropdown_list",
                      _activeStyleVariant
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-f898fa14-e9c4-646a-b332-c95900470b06-00470afa"
                    )}
                    tag="ul"
                    unstyled={false}
                  >
                    <ListItem
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_item",
                        _activeStyleVariant
                      )}
                    >
                      <Link
                        block="inline"
                        button={false}
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_link",
                          _activeStyleVariant
                        )}
                        options={{
                          href: "#",
                        }}
                      >
                        <Block
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Branding"}
                        </Block>
                      </Link>
                    </ListItem>
                    <ListItem
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_item",
                        _activeStyleVariant
                      )}
                    >
                      <Link
                        block="inline"
                        button={false}
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_link",
                          _activeStyleVariant
                        )}
                        options={{
                          href: "#",
                        }}
                      >
                        <Block
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Website Design"}
                        </Block>
                      </Link>
                    </ListItem>
                    <ListItem
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_item",
                        _activeStyleVariant
                      )}
                    >
                      <Link
                        block="inline"
                        button={false}
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_link",
                          _activeStyleVariant
                        )}
                        options={{
                          href: "#",
                        }}
                      >
                        <Block
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_text",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Development"}
                        </Block>
                      </Link>
                    </ListItem>
                  </List>
                </Block>
              </Block>
            </DropdownList>
          </DropdownWrapper>
        </ListItem>
        <ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            delay={400}
            hover={true}
            tag="div"
          >
            <DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              data-state="expanded"
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_links_text",
                  _activeStyleVariant
                )}
                tag="div"
              >
                {"Work"}
              </Block>
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_links_svg",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconArrow direction="Bottom" />
              </Block>
            </DropdownToggle>
            <DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_mega_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_mega_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "nav_dropdown_mega_scroll",
                    _activeStyleVariant
                  )}
                  data-lenis-prevent=""
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "nav_dropdown_mega_contain",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <Block
                      className={_utils.cx(
                        _styles,
                        "nav_dropdown_mega_layout",
                        _activeStyleVariant
                      )}
                      tag="div"
                    >
                      <List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b1f-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </Block>
                          </Link>
                        </ListItem>
                      </List>
                      <List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b2c-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </Block>
                          </Link>
                        </ListItem>
                      </List>
                      <List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b39-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </Block>
                          </Link>
                        </ListItem>
                      </List>
                      <List
                        className={_utils.cx(
                          _styles,
                          "nav_dropdown_list",
                          _activeStyleVariant
                        )}
                        id={_utils.cx(
                          _styles,
                          "w-node-f898fa14-e9c4-646a-b332-c95900470b46-00470afa"
                        )}
                        tag="ul"
                        unstyled={false}
                      >
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Branding"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Website Design"}
                            </Block>
                          </Link>
                        </ListItem>
                        <ListItem
                          className={_utils.cx(
                            _styles,
                            "nav_dropdown_item",
                            _activeStyleVariant
                          )}
                        >
                          <Link
                            block="inline"
                            button={false}
                            className={_utils.cx(
                              _styles,
                              "nav_dropdown_link",
                              _activeStyleVariant
                            )}
                            options={{
                              href: "#",
                            }}
                          >
                            <Block
                              className={_utils.cx(
                                _styles,
                                "nav_dropdown_text",
                                _activeStyleVariant
                              )}
                              tag="div"
                            >
                              {"Development"}
                            </Block>
                          </Link>
                        </ListItem>
                      </List>
                    </Block>
                  </Block>
                </Block>
              </Block>
            </DropdownList>
          </DropdownWrapper>
        </ListItem>
        <ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <Link
            block="inline"
            button={false}
            className={_utils.cx(
              _styles,
              "nav_links_link",
              _activeStyleVariant
            )}
            options={{
              href: "#",
            }}
          >
            <Block
              className={_utils.cx(
                _styles,
                "nav_links_text",
                _activeStyleVariant
              )}
              tag="div"
            >
              {"About"}
            </Block>
          </Link>
        </ListItem>
        <ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <Link
            block="inline"
            button={false}
            className={_utils.cx(
              _styles,
              "nav_links_link",
              _activeStyleVariant
            )}
            options={{
              href: "#",
            }}
          >
            <Block
              className={_utils.cx(
                _styles,
                "nav_links_text",
                _activeStyleVariant
              )}
              tag="div"
            >
              {"Contact"}
            </Block>
          </Link>
        </ListItem>
      </List>
      <List
        className={_utils.cx(_styles, "nav_actions_wrap", _activeStyleVariant)}
        tag="ul"
        unstyled={true}
      >
        <ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            delay={400}
            hover={false}
            tag="div"
          >
            <DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              data-state="expanded"
              tag="div"
            >
              <NotSupported _atom="Locales Wrapper" />
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_links_svg",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconArrow direction="Bottom" />
              </Block>
            </DropdownToggle>
            <DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_main_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_main_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <NotSupported _atom="Locales Wrapper" />
              </Block>
            </DropdownList>
          </DropdownWrapper>
        </ListItem>
        <ListItem
          className={_utils.cx(_styles, "nav_links_item", _activeStyleVariant)}
        >
          <DropdownWrapper
            className={_utils.cx(
              _styles,
              "nav_dropdown_component",
              _activeStyleVariant
            )}
            data-open-on-mobile=""
            delay={400}
            hover={false}
            tag="div"
          >
            <DropdownToggle
              className={_utils.cx(
                _styles,
                "nav_links_link",
                _activeStyleVariant
              )}
              data-state="expanded"
              tag="div"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_links_search_icon",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <IconSearch />
              </Block>
              <Block
                className={_utils.cx(_styles, "u-sr-only", _activeStyleVariant)}
                tag="div"
              >
                {"Search"}
              </Block>
            </DropdownToggle>
            <DropdownList
              className={_utils.cx(
                _styles,
                "nav_dropdown_mega_wrap",
                _activeStyleVariant
              )}
              tag="nav"
            >
              <Block
                className={_utils.cx(
                  _styles,
                  "nav_dropdown_mega_content",
                  _activeStyleVariant
                )}
                tag="div"
              >
                <Block
                  className={_utils.cx(
                    _styles,
                    "nav_dropdown_mega_scroll",
                    _activeStyleVariant
                  )}
                  data-lenis-prevent=""
                  tag="div"
                >
                  <Block
                    className={_utils.cx(
                      _styles,
                      "nav_dropdown_mega_contain",
                      _activeStyleVariant
                    )}
                    tag="div"
                  >
                    <SearchForm
                      action="/search"
                      className={_utils.cx(
                        _styles,
                        "nav_search_wrap",
                        _activeStyleVariant
                      )}
                    >
                      <DOM
                        className={_utils.cx(
                          _styles,
                          "nav_search_btn_wrap",
                          _activeStyleVariant
                        )}
                        slot=""
                        tabindex="-1"
                        tag="button"
                        type="submit"
                      >
                        <DOM
                          aria-hidden="true"
                          className={_utils.cx(
                            _styles,
                            "nav_search_btn_icon",
                            _activeStyleVariant
                          )}
                          fill="none"
                          slot=""
                          tag="svg"
                          viewBox="0 0 400 400"
                          width="100%"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <DOM
                            cx="171"
                            cy="171"
                            r="155"
                            slot=""
                            stroke="currentColor"
                            stroke-width="var(--nav--icon-thickness)"
                            tag="circle"
                            vector-effect="non-scaling-stroke"
                          />
                          <DOM
                            d="M280.602 280.602L388.602 388.602"
                            slot=""
                            stroke="currentColor"
                            stroke-width="var(--nav--icon-thickness)"
                            tag="path"
                            vector-effect="non-scaling-stroke"
                          />
                        </DOM>
                        <Block
                          className={_utils.cx(
                            _styles,
                            "u-sr-only",
                            _activeStyleVariant
                          )}
                          tag="div"
                        >
                          {"Search"}
                        </Block>
                      </DOM>
                      <DOM
                        className={_utils.cx(
                          _styles,
                          "nav_search_label",
                          _activeStyleVariant
                        )}
                        slot=""
                        tag="label"
                      >
                        <DOM
                          className={_utils.cx(
                            _styles,
                            "u-sr-only",
                            _activeStyleVariant
                          )}
                          slot=""
                          tag="span"
                        >
                          {"Search"}
                        </DOM>
                        <SearchInput
                          autoFocus={false}
                          className={_utils.cx(
                            _styles,
                            "nav_search_field",
                            _activeStyleVariant
                          )}
                          disabled={false}
                          id={_utils.cx(_styles, "search-2")}
                          maxLength={256}
                          name="query"
                          placeholder="Search…"
                          required={true}
                          type="search"
                        />
                      </DOM>
                      <SearchButton
                        className={_utils.cx(
                          _styles,
                          "u-display-none",
                          _activeStyleVariant
                        )}
                        type="submit"
                        value="Search"
                      />
                    </SearchForm>
                  </Block>
                </Block>
              </Block>
            </DropdownList>
          </DropdownWrapper>
        </ListItem>
        <ListItem
          className={_utils.cx(
            _styles,
            "nav_buttons_item",
            "is-main",
            _activeStyleVariant
          )}
        >
          <ButtonMain variant="Secondary" />
        </ListItem>
        <ListItem
          className={_utils.cx(
            _styles,
            "nav_buttons_item",
            _activeStyleVariant
          )}
        >
          <ButtonMain variant="Primary" />
        </ListItem>
      </List>
    </_Component>
  );
}
